[package]
name = "pyo3-derive-backend"
version = "0.8.4"
description = "Code generation for PyO3 package"
authors = ["PyO3 Project and Contributors <https://github.com/PyO3>"]
keywords = ["pyo3", "python", "cpython", "ffi"]
homepage = "https://github.com/pyo3/pyo3"
repository = "https://github.com/pyo3/pyo3"
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "1", features = ["full", "extra-traits"] }

[features]
unsound-subclass = []
